# Generated by Django 4.1.8 on 2023-04-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_auto_20190831_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
